class SuperBaseSecrets {
  static const supabaseUrl = 'https://rhjednkgteyiggeikrpz.supabase.co';
  static const supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJoamVkbmtndGV5aWdnZWlrcnB6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzEyMTM1MDYsImV4cCI6MjA0Njc4OTUwNn0.QYKFqszrux7qGjR9xnTId0QgH4VGeIbAglT9O5C8VfM';
}